#ifndef HYPERCALL_H
#define HYPERCALL_H

#include <z3.h>
#include <stdio.h>
#include <sys/stat.h>

#if defined(__ILP32__) || defined(_ILP32)
typedef uint32_t uint_t;
#else
typedef uint64_t uint_t;
#endif

typedef Z3_ast SymExpr;

typedef union {
    uint_t uint;
    uint64_t u64;
    uint32_t u32;
    uint8_t u8;
    off64_t off64;
    unsigned u;
    int i;
    double d;
    long l;
    bool b;
    size_t size;
    ssize_t ssize;
    uintptr_t uintptr;  
    mode_t mode;    
    char *str;
    const char *cstr;
    void *ptr; 
    const void *cptr; 
    uint8_t *u8ptr;
    const uint8_t *cu8ptr;
    FILE *fileptr;
    Z3_ast z3;
    SymExpr sym;
    SymExpr *symptr;
} pun_t;

uint_t kAFL_hypercall(uint_t rbx, uint_t rcx, uint_t rdx, uint_t rdi, uint_t rsi, uint_t r8, uint_t r9);

enum Sym {
    INITIALIZE = 1,
    BUILD_INTEGER = 2,
    BUILD_INTEGER128 = 3,
    BUILD_INTEGER_FROM_BUFFER = 4,
    BUILD_FLOAT = 5,
    GET_INPUT_BYTE = 6,
    BUILD_NULL_POINTER = 7,
    BUILD_TRUE = 8,
    BUILD_FALSE = 9,
    BUILD_BOOL = 10,
    BUILD_NEG = 11,
    BUILD_ADD = 12,
    BUILD_SUB = 13,
    BUILD_MUL = 14,
    BUILD_UNSIGNED_DIV = 15,
    BUILD_SIGNED_DIV = 16,
    BUILD_UNSIGNED_REM = 17,
    BUILD_SIGNED_REM = 18,
    BUILD_SHIFT_LEFT = 19,
    BUILD_LOGICAL_SHIFT_RIGHT = 20,
    BUILD_ARITHMETIC_SHIFT_RIGHT = 21,
    BUILD_SIGNED_LESS_THAN = 22,
    BUILD_SIGNED_LESS_EQUAL = 23,
    BUILD_SIGNED_GREATER_THAN = 24,
    BUILD_SIGNED_GREATER_EQUAL = 25,
    BUILD_UNSIGNED_LESS_THAN = 26,
    BUILD_UNSIGNED_LESS_EQUAL = 27,
    BUILD_UNSIGNED_GREATER_THAN = 28,
    BUILD_UNSIGNED_GREATER_EQUAL = 29,
    BUILD_EQUAL = 30,
    BUILD_AND = 31,
    BUILD_OR = 32,
    BUILD_BOOL_XOR = 33,
    BUILD_XOR = 34,
    BUILD_FLOAT_ORDERED_GREATER_THAN = 35,
    BUILD_FLOAT_ORDERED_GREATER_EQUAL = 36,
    BUILD_FLOAT_ORDERED_LESS_THAN = 37,
    BUILD_FLOAT_ORDERED_LESS_EQUAL = 38,
    BUILD_FLOAT_ORDERED_EQUAL = 39,
    BUILD_ITE = 40,
    BUILD_FP_ADD = 41,
    BUILD_FP_SUB = 42,
    BUILD_FP_MUL = 43,
    BUILD_FP_DIV = 44,
    BUILD_FP_REM = 45,
    BUILD_FP_ABS = 46,
    BUILD_FP_NEG = 47,
    BUILD_NOT = 48,
    BUILD_NOT_EQUAL = 49,
    BUILD_BOOL_AND = 50,
    BUILD_BOOL_OR = 51,
    BUILD_FLOAT_ORDERED_NOT_EQUAL = 52,
    BUILD_FLOAT_ORDERED = 53,
    BUILD_FLOAT_UNORDERED = 54,
    BUILD_FLOAT_UNORDERED_GREATER_THAN = 55,
    BUILD_FLOAT_UNORDERED_GREATER_EQUAL = 56,
    BUILD_FLOAT_UNORDERED_LESS_THAN = 57,
    BUILD_FLOAT_UNORDERED_LESS_EQUAL = 58,
    BUILD_FLOAT_UNORDERED_EQUAL = 59,
    BUILD_FLOAT_UNORDERED_NOT_EQUAL = 60,
    BUILD_SEXT = 61,
    BUILD_ZEXT = 62,
    BUILD_TRUNC = 63,
    BUILD_INT_TO_FLOAT = 64,
    BUILD_FLOAT_TO_FLOAT = 65,
    BUILD_BITS_TO_FLOAT = 66,
    BUILD_FLOAT_TO_BITS = 67,
    BUILD_FLOAT_TO_SIGNED_INTEGER = 68,
    BUILD_FLOAT_TO_UNSIGNED_INTEGER = 69,
    BUILD_BOOL_TO_BIT = 70,
    PUSH_PATH_CONSTRAINT = 71,
    CONCAT_HELPER = 72,
    EXTRACT_HELPER = 73,
    BITS_HELPER = 74,
    NOTIFY_CALL = 75,
    NOTIFY_RET = 76,
    NOTIFY_BASIC_BLOCK = 77,
    EXPR_TO_STRING = 78,
    FEASIBLE = 79,
    COLLECT_GARBAGE = 80,
    BUILD_BIT_TO_BOOL = 81,
    SET_RETURN_EXPRESSION = 82,
    GET_RETURN_EXPRESSION = 83,
    SET_PARAMETER_EXPRESSION = 84,
    GET_PARAMETER_EXPRESSION = 85,
    READ_MEMORY = 86,
    WRITE_MEMORY = 87,
    BUILD_EXTRACT = 88,
    BUILD_BSWAP = 89,
    BUILD_INSERT = 90,
    BUILD_ZERO_BYTES = 91,
    BUILD_SADD_SAT = 92,
    BUILD_UADD_SAT = 93,
    BUILD_SSUB_SAT = 94,
    BUILD_USUB_SAT = 95,
    BUILD_SHIFT_LEFT_OVERFLOW = 96,
    BUILD_SSHL_SAT = 97,
    BUILD_USHL_SAT = 98,
    BUILD_ADD_OVERFLOW = 99,
    BUILD_SUB_OVERFLOW = 100,
    BUILD_MUL_OVERFLOW = 101,
    BUILD_FUNNEL_SHIFT_LEFT = 102,
    BUILD_FUNNEL_SHIFT_RIGHT = 103,
    BUILD_ABS = 104,
    REGISTER_EXPRESSION_REGION = 105,
    MAKE_SYMBOLIC = 106,
    SYMCC_MAKE_SYMBOLIC = 107,
    MALLOC = 108,
    CALLOC = 109,
    MMAP = 110,
    MMAP64 = 111,
    OPEN = 112,
    READ = 113,
    LSEEK = 114,
    LSEEK64 = 115,
    FOPEN = 116,
    FOPEN64 = 117,
    FREAD = 118,
    FSEEK = 119,
    FSEEKO = 120,
    REWIND = 121,
    FSEEKO64 = 122,
    GETC = 123,
    UNGETC = 124,
    MEMCPY = 125,
    MEMSET = 126,
    STRNCPY = 127,
    STRCHR = 128,
    MEMCMP = 129,
    MEMMOVE = 130,
    NTOHL = 131,
    FGETS = 132,
    FGETC = 133,
    GETCHAR = 134,
    BCOPY = 135,
    BCMP = 136,
    BZERO = 137,
};


#endif // HYPERCALL_H
